### ISSUE TITLE
虫子把我图片吃了 BUG ate my pictures.

### ISSUE THREAD

**Issue by ZCTskyy** [JcxAu/ReptilePy#1]
![8b9324195be70ef5c2fe6a2e744dbd49](https://github.com/JcxAu/ReptilePy/assets/96329702/e6138390-69ba-470e-86ef-d4fafcacb933)
![7f08dd87bb8db7a4e3b97d98f0772180](https://github.com/JcxAu/ReptilePy/assets/96329702/aed199b7-b9e6-428f-895c-807186c75dbe)
![d187e7784a8362d4d09b485fc07c59e1](https://github.com/JcxAu/ReptilePy/assets/96329702/c7d5204d-c7b4-4cf9-87b3-61b38a6d4a0c)
![20be839eccd935680699f194092fbe7c](https://github.com/JcxAu/ReptilePy/assets/96329702/d8f2841b-84ad-4fee-b9a5-212479eb3615)

RT，我在使用您的 ReptilePy_ver1.2_Nuitka.exe 时出现了以上状况：info.log & 下载报告显示爬取了 99 张图片，实际只有 98 张，而且出现了下载图片编号不连续的状况。请问能否修正这个 bug 呢？thx。

As above, the above situation occurred when I used your ReptilePy_ver1.2_Nuitka.exe: info.log & download report showed that 99 pictures were crawled, but in fact there were only 98, and the downloaded picture numbers were discontinuous. Could you please fix this bug? thx.

附上 info.log & config 文件。 Attached info.log & config files.

[download_info.log](https://github.com/JcxAu/ReptilePy/files/14495826/download_info.log)
[config.zip](https://github.com/JcxAu/ReptilePy/files/14495860/config.zip)

**Comment by JcxAu** [comment]
I don't know the reason of the bug appearing yet.
But I'll try my best to repair the bug.
Thanks for feedbacking.
: )

**Comment by JcxAu** [comment]
Perhaps I have solved this problem now.
